### ISSUE TITLE
Device management seems to have a bug.

### ISSUE THREAD

**Issue by icewired-yy** [ksang/height2normal#1]
Hello, thanks for sharing your nice code.

I find a slight bug in your forward process of `HeightToNormal` in `h2n.py`. When passing a height map on `CUDA` device, it will encounter a exception of operating two tensors of two different devices. From your code I think that you want to dynamically adapt the input of different devices, since you have coded `dx.device`. 

Maybe we can fix the bug by dynamically detecting the device of input, and modifying the device of `self.filter_kernel` and `self.blur`. Like:
```
    # Expecting input height is a tensor in shape [B, C, H, W] and in value range [0, 1]
    def forward(self, height):
        device_of_height = height.device
        self.filter_kernel = self.filter_kernel.to(device_of_height)
        self.blur = self.blur.to(device_of_height)

        x = self.filter(height)
        dx = -1.0 * x[:, 0] if self.invert_x else x[:, 0]
        dy = -1.0 * x[:, 1] if self.invert_y else x[:, 1]
        normal = torch.stack([dx, dy, torch.ones(dx.shape, device=device_of_height) / self.strength], dim=1)
        normal = torch.nn.functional.normalize(normal, dim=1)
        return normal
```

**Comment by ksang** [comment]
Thanks, fixed in 459aa6cc2709116ea46c20f1356f889c39f9abe2
